"""Validate all canonical output: semantic (metadata_model.json) then dashboard (dashboard_metadata.json).

Validates each report folder under canonical_output by parsing JSON into MetadataModel and
DashboardMetadata. Writes results to validation/canonical_validation_report.md.
Also validates that dashboard field references (datasource_id, field_id) resolve in the semantic model;
see validation/semantic_dashboard_relationship.md and semantic_dashboard_crossref_report.md.
Run: uv run pytest tests/validation/ -v
"""

import json
import os
from pathlib import Path

import pytest

from powerbi_to_looker.models.canonical import MetadataModel
from powerbi_to_looker.models.dashboard import DashboardMetadata

# Repo root: tests/validation/test_canonical_output.py -> parent.parent.parent
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_VALIDATION_DIR = _REPO_ROOT / "validation"
_REPORT_PATH = _VALIDATION_DIR / "canonical_validation_report.md"
_CROSSREF_REPORT_PATH = _VALIDATION_DIR / "semantic_dashboard_crossref_report.md"


def _canonical_output_dir() -> Path:
    path = os.environ.get("CANONICAL_OUTPUT_DIR")
    if path:
        return Path(path).resolve()
    return _REPO_ROOT / "canonical_output"


def _report_folders(canonical_dir: Path) -> list[Path]:
    if not canonical_dir.is_dir():
        return []
    out = []
    for p in canonical_dir.iterdir():
        if p.is_dir() and not p.name.startswith("_"):
            if (p / "metadata_model.json").exists() or (p / "dashboard_metadata.json").exists():
                out.append(p)
    return sorted(out, key=lambda x: x.name)


def _validate_semantic(report_dir: Path) -> tuple[bool, str]:
    path = report_dir / "metadata_model.json"
    if not path.exists():
        return False, "metadata_model.json missing"
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        MetadataModel.model_validate(data)
        return True, ""
    except Exception as e:
        return False, str(e)


def _validate_dashboard(report_dir: Path) -> tuple[bool, str]:
    path = report_dir / "dashboard_metadata.json"
    if not path.exists():
        return False, "dashboard_metadata.json missing"
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        DashboardMetadata.model_validate(data)
        return True, ""
    except Exception as e:
        return False, str(e)


def _write_report(rows: list[dict], report_path: Path) -> None:
    report_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Canonical output validation report",
        "",
        "Generated by `pytest tests/validation/`. Validates each report's semantic (metadata_model.json) and dashboard (dashboard_metadata.json) against Pydantic schemas.",
        "",
        "| Report | Semantic | Dashboard | Notes |",
        "|--------|----------|-----------|-------|",
    ]
    pass_count = 0
    for r in rows:
        report_id = r["report_id"]
        sem = r["semantic_status"]
        dash = r["dashboard_status"]
        notes = r.get("notes", "")
        if sem == "OK" and dash == "OK":
            pass_count += 1
        lines.append(f"| {report_id} | {sem} | {dash} | {notes} |")
    lines.extend(["", f"**Total:** {len(rows)} report(s). **Passed:** {pass_count}/{len(rows)} (semantic and dashboard both OK).", ""])
    report_path.write_text("\n".join(lines), encoding="utf-8")


def test_canonical_output_valid_and_report_generated():
    """Validate all canonical output (semantic then dashboard) and write validation/canonical_validation_report.md."""
    canonical_dir = _canonical_output_dir()
    if not canonical_dir.is_dir():
        pytest.skip(f"Canonical output dir not found: {canonical_dir}")

    report_dirs = _report_folders(canonical_dir)
    if not report_dirs:
        pytest.skip(f"No report folders in {canonical_dir}")

    rows = []
    all_ok = True
    for report_dir in report_dirs:
        report_id = report_dir.name
        sem_ok, sem_err = _validate_semantic(report_dir)
        dash_ok, dash_err = _validate_dashboard(report_dir)
        if not sem_ok or not dash_ok:
            all_ok = False
        sem_status = "OK" if sem_ok else "FAIL"
        dash_status = "OK" if dash_ok else "FAIL"
        notes = ""
        if sem_err:
            notes = notes + (" " if notes else "") + f"Semantic: {sem_err}"
        if dash_err:
            notes = notes + (" " if notes else "") + f"Dashboard: {dash_err}"
        rows.append({
            "report_id": report_id,
            "semantic_status": sem_status,
            "dashboard_status": dash_status,
            "notes": notes.strip(),
        })

    _write_report(rows, _REPORT_PATH)
    assert all_ok, f"Some validations failed. See {_REPORT_PATH}"


def _semantic_field_keys(metadata_model: MetadataModel) -> set[tuple[str, str]]:
    """Set of (source_table, field_name) for all fields in the semantic model."""
    out: set[tuple[str, str]] = set()
    for ds in metadata_model.datasources:
        for f in ds.fields:
            st = (f.source_table or "").strip()
            name = (f.name or "").strip()
            if st and name:
                out.add((st, name))
    return out


def _dashboard_field_refs(dashboard_metadata: DashboardMetadata) -> set[tuple[str, str]]:
    """Set of (datasource_id, field_id) from visualizations' data_mappings and filter_components."""
    out: set[tuple[str, str]] = set()
    for viz in dashboard_metadata.visualizations:
        for m in viz.data_mappings:
            ds = (m.datasource_id or "").strip()
            fid = (m.field_id or "").strip()
            if ds and fid:
                out.add((ds, fid))
    for fc in dashboard_metadata.filter_components:
        ds = (fc.datasource_id or "").strip()
        fid = (fc.field_id or "").strip()
        if ds and fid:
            out.add((ds, fid))
    return out


def _validate_semantic_dashboard_crossref(report_dir: Path) -> tuple[bool, str, int]:
    """
    Check that every (datasource_id, field_id) in dashboard exists in semantic (source_table, name).
    Returns (ok, error_detail, missing_count).
    """
    meta_path = report_dir / "metadata_model.json"
    dash_path = report_dir / "dashboard_metadata.json"
    if not meta_path.exists() or not dash_path.exists():
        return False, "missing file", 0
    try:
        with open(meta_path, encoding="utf-8") as f:
            meta = MetadataModel.model_validate(json.load(f))
        with open(dash_path, encoding="utf-8") as f:
            dash = DashboardMetadata.model_validate(json.load(f))
    except Exception as e:
        return False, str(e), 0
    valid_keys = _semantic_field_keys(meta)
    refs = _dashboard_field_refs(dash)
    missing = refs - valid_keys
    if not missing:
        return True, "", 0
    return False, f"{len(missing)} ref(s) not in semantic: " + ", ".join(f"{a}.{b}" for a, b in sorted(missing)[:5]) + (" ..." if len(missing) > 5 else ""), len(missing)


def test_semantic_dashboard_crossref_and_report():
    """Ensure dashboard (datasource_id, field_id) resolve in semantic; write semantic_dashboard_crossref_report.md."""
    canonical_dir = _canonical_output_dir()
    if not canonical_dir.is_dir():
        pytest.skip(f"Canonical output dir not found: {canonical_dir}")

    report_dirs = _report_folders(canonical_dir)
    if not report_dirs:
        pytest.skip(f"No report folders in {canonical_dir}")

    rows: list[dict] = []
    all_ok = True
    for report_dir in report_dirs:
        report_id = report_dir.name
        ok, detail, missing_count = _validate_semantic_dashboard_crossref(report_dir)
        if not ok:
            all_ok = False
        status = "OK" if ok else "FAIL"
        rows.append({"report_id": report_id, "status": status, "detail": detail or "", "missing_count": missing_count})

    _VALIDATION_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Semantic–dashboard cross-reference validation report",
        "",
        "Checks that every dashboard field reference `(datasource_id, field_id)` exists in the semantic model as `(Field.source_table, Field.name)`. See `semantic_dashboard_relationship.md`.",
        "",
        "| Report | Status | Notes |",
        "|--------|--------|-------|",
    ]
    for r in rows:
        lines.append(f"| {r['report_id']} | {r['status']} | {r['detail'] or '-'} |")
    pass_count = sum(1 for r in rows if r["status"] == "OK")
    lines.extend(["", f"**Passed:** {pass_count}/{len(rows)} report(s) with all dashboard refs resolving in semantic.", ""])
    _CROSSREF_REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")
    assert all_ok, f"Some dashboard refs do not resolve in semantic. See {_CROSSREF_REPORT_PATH}"
